use_frameworks!

source 'http://gitlab.fallrainy.top/root/XDBSpecs.git'
source 'https://github.com/CocoaPods/Specs.git' #官方仓库的地址

target 'WLTableViewManager_Example' do
  
#  pod 'WLTableViewManager'

#  pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
  pod 'WLTableViewManager', :path => '../'
  
  
#
#  target 'WLTableViewManager_Tests' do
#    inherit! :search_paths
#
#  end
end
